apiVersion: v1
kind: ConfigMap
metadata:
  name: klovercloud-operator-cm
  namespace: klovercloud
data:
  AGENT_OPERATOR_IMAGE_REPOSITORY: "quay.io/klovercloud/klovercloud-agent-operator"
  AGENT_OPERATOR_CHART_NAME: "klovercloud-charts/klovercloud-agent-operator"
  AGENT_OPERATOR_IMAGE_TAG: "poc-v1.3.0"
  AGENT_OPERATOR_CHART_VERSION: "1.1.0"
  IMAGE_PULL_SECRET: ""
  IMAGE_PULL_POLICY: "Always"
  OPERATOR_SERVICE_UPDATE_ENABLED: "true"
  USE_SERVICE_ENDPOINT_IN_CLUSTER_ONBOARD_HELM_COMMAND: "true"
  CONTAINER_REGISTRY_URL: "quay.io/klovercloud"
  READ_WRITE_MANY_STORAGE_CLASS: "local-path"
  READ_WRITE_ONCE_STORAGE_CLASS: "local-path"
  SERVICE_ACCOUNT: ""
  NAMESPACE: "klovercloud"
  TEMPORAL_HOST: "temporal-frontend.temporal:7233"
  TEMPORAL_NAMESPACE: "default"
  SERVICE_DOMAIN_WILDCARD: "kc-operator.klovercloud.com"
  SERVICE_DOMAIN_WILDCARD_TLS_SECRET: ""
  FACADE_ENDPOINT: "http://api.kc-operator.klovercloud.com"
  WEBAPP_ENDPOINT: "http://console.kc-operator.klovercloud.com"
  LISTENER_ENDPOINT: "http://listener.kc-operator.klovercloud.com"
  LIGHT_HOUSE_ENDPOINT: "http://lighthouse.kc-operator.klovercloud.com"
  PROXY_SERVER_ENDPOINT: "http://proxy.kc-operator.klovercloud.com"
  MULTICLUSTER_CONSOLE_GATEWAY_ENDPOINT: "http://gateway.kc-operator.klovercloud.com"
  FACADE_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  WEBAPP_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  LISTENER_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  LIGHT_HOUSE_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  PROXY_SERVER_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  MULTICLUSTER_CONSOLE_GATEWAY_LOAD_BALANCER_SERVICE_EXTERNAL_IPS: ""
  DISABLE_INGRESS_CREATION: "false"
  CREATE_PATH_BASED_INGRESS: "false"
  EXPOSE_SERVICE_AS_LOAD_BALANCER: "false"
  INGRESS_CLASS: "nginx"
  INGRESS_CONTROLLER_TYPE: "NGINX"
  COMPANY: "KloverCloud"
  MONGO_STORAGE_IN_MB: "5120"
  CENTRAL_ARGOCD: "false"
  PLATFORM_SERVICE_LOG_MODE: "INFO"
  ADD_SERVICE_DOMAIN_CONFIG_IN_CLUSTER_ONBOARD_HELM_COMMAND: "true"
  INTERNAL_SERVICE_REQUEST_THROUGH_EXTERNAL_ENDPOINT: "false"
  USE_RESOURCE_TO_SERVICE: "true"
  MONGO_SERVER: ""
  KAFKA_SERVER: ""
  REDIS_HOST: ""
  REDIS_PORT: ""
