apiVersion: v1
kind: Secret
metadata:
  name: klovercloud-operator-secret
  namespace: klovercloud
data:
  COMPANY_ADMIN_EMAIL: "YWRtaW5Aa2xvdmVyY2xvdWQuY29t"
  COMPANY_ADMIN_PASSWORD: "QWRtaW4xMjMh"
  MONGO_USERNAME: "cm9vdA=="
  MONGO_PASSWORD: "NXVaTHZXVXJ2Sg=="
  REDIS_PASSWORD: "NXVrZkx2V1Vydko="
